books/urls.py
from django.urls import path
from . import views


app_name = 'books'

urlpatterns = [
    path('', views.BookModelView.as_view(), name='index'),

    path('book/', views.BookList.as_view(), name='book_list'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),

    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),

    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('books/', include('books.urls')),
]

polls/urls.py
from django.urls import path

from polls import views


app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/results/', views.results, name='results'),
]

books/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ManyToManyField('Author')
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    publication_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Author(models.Model):
    name = models.CharField(max_length=50)
    salutation = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

books/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView

from .models import Book, Author, Publisher


# Template View
class BookModelView(TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_list'] = ['Book', 'Author', 'Publisher']
        return context


# List View
class BookList(ListView):
    model = Book
    template_name = 'books/list/book_list.html'

class AuthorList(ListView):
    model = Author
    template_name = 'books/list/author_list.html'

class PublisherList(ListView):
    model = Publisher
    template_name = 'books/list/publisher_list.html'


# Detail View
class BookDetail(DetailView):
    model = Book
    template_name = 'books/detail/book_detail.html'

class AuthorDetail(DetailView):
    model = Author
    template_name = 'books/detail/author_detail.html'

class PublisherDetail(DetailView):
    model = Publisher
    template_name = 'books/detail/publisher_detail.html'

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpRequest, HttpResponse

from polls.models import Question, Choice


def index(request: HttpRequest) -> HttpResponse:
    latest_question_list = Question.objects.all().order_by('-created_at')
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request: HttpRequest, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def vote(request: HttpRequest, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        context = {'question': question,
                   'error_message': "하나를 선택해 주세요."}
        return render(request, 'polls/detail.html', context)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return redirect('polls:results', question_id=question_id)


def results(request: HttpRequest, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}">
    <title>{% block title %}My Site{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
            <ul>
                <li><a href="/" >Project_Home</a></li>
                <li><a href="/admin">Admin Page</a></li>
            </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/books/base_books.html
{% extends 'base.html' %}

{% block title %} Books Application Site {% endblock %}

{% block sidebar %}
    {{ block.super }}
    <ul>
        <li><a href="{% url 'books:index' %}">Books_Home</a> </li>
    </ul>
{% endblock %}

templates/books/detail/author_detail.html
{% extends 'books/base_books.html' %}

{% block content %}
    <h1>{{ author.name }}</h1>
    <br>
    <ul>
        <li>{{ author.salutation }}</li>
        <li>Author Email : {{ author.email }}</li>
    </ul>
{% endblock %}

templates/books/detail/book_detail.html
{% extends 'books/base_books.html' %}

{% block content %}
    <h1>{{ book.title }}</h1>
    <br>
    <ul>
        <li>Author :
            {% for author in book.author_set.all %}
                {{ author }}
                {% if not forloop.last %}, {% else %}{% endif %}
            {% endfor %}
        </li>
        <li>Publisher : {{ book.publisher }}</li>
        <li>Publication Date : {{ book.publication_date }}</li>
    </ul>
{% endblock %}

templates/books/detail/publisher_detail.html
{% extends 'books/base_books.html' %}

{% block content %}
    <h1>{{ publisher.name }}</h1>
    <br>
    <ul>
        <li>{{ publisher.website }}</li>
        <li>Publisher Address : {{ publisher.address }}</li>
    </ul>
{% endblock %}

templates/books/index.html
{% extends 'books/base_books.html' %}

{% block content %}
    <h2>Books Management System</h2>
    <ul>
        {% for modelname in model_list %}
            {% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
                <li><a href="{% url urlvar %}">{{ modelname }}</a> </li>
            {% endwith %}
        {% endfor %}
    </ul>
{% endblock %}

templates/books/list/author_list.html
{% extends 'books/base_books.html' %}

{% block content %}
    <h2>Author List</h2>
    <ul>
        {% for author in author_list %}
            <li><a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a> </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/books/list/book_list.html
{% extends 'books/base_books.html' %}

{% block content %}
    <h2>Book List</h2>
    <ul>
        {% for book in book_list %}
            <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a> </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/books/list/publisher_list.html
{% extends 'books/base_books.html' %}

{% block content %}
    <h2>Publisher List</h2>
    <ul>
        {% for publisher in publisher_list %}
            <li><a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a> </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div id="container">
    <h2>My Applications</h2>
    <ul>
        <li><a href="{% url 'polls:index' %}">Poll Application</a></li>
        <li><a href="{% url 'books:index' %}">Book Application</a></li>
    </ul>
</div>
{% endblock %}

templates/polls/base.html
{% extends 'base.html' %}
<fieldset>
    {% block sidebar %}
        {{ block.super }}
        <ul>
            <li><a href="{% url 'polls:index' %}">Polls Home</a> </li>
        </ul>
    {% endblock %}

    {% block content %}
    {% endblock %}
</fieldset>

templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
    <legend><h1>{{ question.question_text }}</h1></legend>
    <form method="POST" action="{% url 'polls:vote' question.id %}">
        {% csrf_token %}
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <br>
        <input type="submit" value="선택">
    </form>
{% endblock %}

templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
    <legend><h1> 설문 리스트</h1></legend>
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>생성된 설문이 없습니다.</p>
    {% endif %}
{% endblock %}

templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
<legend><h1>{{ question.question_text }}의 투표 결과</h1></legend>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
    <a href="{% url 'polls:index' %}">홈으로</a>
{% endblock %}